# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest


    strategy:
      matrix:
        node-version: [12.x]


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Clone git repository under $GITHUB_WORKSPACE
      uses: actions/checkout@v2

    - name: Install all dependencies
      run: npm install

    - name: Install missing libgbm.so
      run: sudo apt-get install -y libgbm

    - name: Run all tests and ensure 100% coverage
      run: npm run coverage

    - name: Clean up working directory
      run: rm -rf node_modules .github .idea .nyc_output resource .gitignore package*.json *.test.js

    - name: Deploy on ruben-quast.fr
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: ${{ secrets.FTP_SERVER }}
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        localDir: "."
        remoteDir: "/public/www/uga/inf402"


